package ent;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 01 12:48:49 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Deptno {
            public Object get(DeptImpl obj) {
                return obj.getDeptno();
            }

            public void put(DeptImpl obj, Object value) {
                obj.setDeptno((Number)value);
            }
        }
        ,
        Dname {
            public Object get(DeptImpl obj) {
                return obj.getDname();
            }

            public void put(DeptImpl obj, Object value) {
                obj.setDname((String)value);
            }
        }
        ,
        Loc {
            public Object get(DeptImpl obj) {
                return obj.getLoc();
            }

            public void put(DeptImpl obj, Object value) {
                obj.setLoc((String)value);
            }
        }
        ,
        Emp {
            public Object get(DeptImpl obj) {
                return obj.getEmp();
            }

            public void put(DeptImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DeptImpl object);

        public abstract void put(DeptImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DEPTNO = AttributesEnum.Deptno.index();
    public static final int DNAME = AttributesEnum.Dname.index();
    public static final int LOC = AttributesEnum.Loc.index();
    public static final int EMP = AttributesEnum.Emp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DeptImpl() {
    }

    /**
     * Gets the attribute value for Deptno, using the alias name Deptno.
     * @return the Deptno
     */
    public Number getDeptno() {
        return (Number)getAttributeInternal(DEPTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deptno.
     * @param value value to set the Deptno
     */
    public void setDeptno(Number value) {
        setAttributeInternal(DEPTNO, value);
    }

    /**
     * Gets the attribute value for Dname, using the alias name Dname.
     * @return the Dname
     */
    public String getDname() {
        return (String)getAttributeInternal(DNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dname.
     * @param value value to set the Dname
     */
    public void setDname(String value) {
        setAttributeInternal(DNAME, value);
    }

    /**
     * Gets the attribute value for Loc, using the alias name Loc.
     * @return the Loc
     */
    public String getLoc() {
        return (String)getAttributeInternal(LOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Loc.
     * @param value value to set the Loc
     */
    public void setLoc(String value) {
        setAttributeInternal(LOC, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmp() {
        return (RowIterator)getAttributeInternal(EMP);
    }

    /**
     * @param deptno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number deptno) {
        return new Key(new Object[]{deptno});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("ent.Dept");
        }
        return mDefinitionObject;
    }
}
